language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - '10'
  - '12'
script:
  - yarn test
jobs:
  include:
    - stage: release
      node_js: '12'
      script:
        - yarn test
        - yarn build
      after_success:
        - yarn report-coverage
        - yarn semantic-release
